### ISSUE TITLE
Image layout='fill'

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#13]
## Description

- layout='fill'은 상위 요소를 기준으로 해당 요소가 꽉 채워진다.
- 상위 요소에 position: relative를 줬다
- 상위 요소에 fill 될때도 있고 body에 fill 될때도 있다.
- 왜이럼?

## To-Do

- [x] Image 태그 살펴보기
- [x] 수정

## ETC
```javascript
<SC.Contents style={{position: 'relative'}}>
                    <Image
                        src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Golde33443.jpg/280px-Golde33443.jpg"
                        alt="개"
                        layout="fill"
                        objectFit="cover" // 이미지를 꽉 채우도록 설정
                    />
```
요렇게 해결

**Comment by Februaar** [comment]
다른 방법 찾아보시고 안되면 layout을 주지말고 width와 height에 100%를 줘봐도 될 거 같아요

**Comment by Daily-manjoo** [comment]
그 위에 상위 요소까지 position 된 건 없나여 아니면 css에 !important 붙여보심이
