### ISSUE TITLE
Refactor: 어플리케이션 최적화

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#177]
## Description
왜인지 모르겠는데 페이지가 갑자기 무지하게 느려졌어요... 페이지 렌더링 약 10초에서 20초 걸리는데....
원인을 찾아서 리팩토링 해볼게요...!

## To-Do

- [ ] 원인찾기
- [ ] SSG로 구현
- [ ] import 구문 리팩토링

## ETC
뭘까 원인이 대체...
![image](https://github.com/inssagram/FE/assets/105287510/f8597e58-b581-4751-bb9a-e0a5ed43500a)

**Comment by Daily-manjoo** [comment]
dpdpdpd에엥 뭐지 저도 찾아보께영
