### ISSUE TITLE
Feat: 게시글 작성 페이지 레이아웃

### ISSUE THREAD

**Issue by Daily-manjoo** [inssagram/FE#27]
## Description
게시글 작성 페이지 구현

## To-Do
- [x] 게시글 작성 페이지 

## ETC
날이 쌀쌀하니 포장마차가 땡기네요

**Comment by Februaar** [comment]
술도 못드시면서 무슨 포창마차세요

**Comment by Daily-manjoo** [comment]
떡볶이 튀김 말한건데요????????? (잼민)
