### ISSUE TITLE
Feature : 로그인 및 게시물 올리기 테스트

### ISSUE THREAD

**Issue by Daily-manjoo** [inssagram/FE#56]
## Description
- test라는 아이디, 비번으로 로그인 시 토큰 발급 받고 메인 페이지 진입

- 게시물을 올리면 마이 페이지 피드에 순서대로 뜨게 하기( 이건 대체 어떻게 해야 할까요 ^^ㅎ 며칠 걸릴듯)

## To-Do
- [x] 메인 페이지 진입
- [x] 게시물 올리기 테스트

**Comment by Februaar** [comment]
게시일자 순으로 정렬해서 렌더링하면 될 거 같아요!

**Comment by joshyeom** [comment]
등록된 id나 순서를 역순으로 해서 불러와도 될거같아요!

**Comment by oinochoe** [comment]
보통 이런 경우에는 게시물을 올리면 현업에서는 백엔드에서 정렬을 해서 주게 됩니다.
주로 백엔드 데이터 베이스에서 registeredDate라는 컬럼을 관리하고 그 컬럼을 기준으로 오름차순으로 정렬해서 주게 됩니다.

현재는 프론트에서 관리할 때도 마찬가지로 날짜 기준으로 정렬하면 될텐데, 수정할 때를 고려한다면? 
수정할 때도 마찬가지로 등록일자 수정일자가 있다면, 인스타그램의 경우에는 수정을 해도 순서가 변경되지 않기 때문에 등록일자로 정렬하면 되겠네요.

```javascript

// 데이터
const posts = [
  { id: 1, content: "post 1번", timestamp: new Date("2023-01-01T12:00:00Z") },
  { id: 2, content: "post 2번", timestamp: new Date("2023-01-02T12:00:00Z") },
  { id: 3, content: "post 3번", timestamp: new Date("2023-01-03T12:00:00Z") },
];

// 포스트 정렬
posts.sort((a, b) => b.timestamp - a.timestamp);

// 피드 컴포넌트 예시
const Feed = () => {
  return (
    <div>
      {posts?.map(post => (
        <div key={post.id}>
          <p>{post.content}</p>
          <small>{post.timestamp.toLocaleString()}</small>
        </div>
      ))}
    </div>
  );
};
...
```
