### ISSUE TITLE
Warn: It looks like there is a custom Babel configuration can be removed 

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#64]
## Description

styled-components의 SSR을 true로 설정해주는 bable을 생성하였더니 babel을 쓰지말고 next.config로 조정하라는 경고 메시지가 뜬다

![image](https://github.com/inssagram/FE/assets/105287510/5252a316-b749-400d-9cc2-0a6167312fbd)

하지만 babel을 지우면 styled-components가 페이지가 이동할때 html이 먼저로드되고 css가 나중에 로드되어 class가 맞지않아 css가 결국 안먹게 되는데 어떻게 해야할까?

## ETC

bable 혹은 next.config 둘중에 하나만 없어도 css가 먹지 않는다
경고 메시지는 무시해도 상관없다는데 괜히 찝찝...

**Comment by oinochoe** [comment]
Next.js의 업데이트는 지속되고 있습니다.
그 기반의 경고문구는 무시해도 됩니다. 아니라면 Next.js를 업데이트하시고 거기에 업데이트 된 기능을 기반으로 사용해주시면 경고문구를 사라지게 할 수 있습니다.

현재 프로젝트에 설치된 next는 13.4.19입니다.

현재는 13.5.5 버전까지 나와있고, 거기에서는 수많은 개발자가 Collaborator로 참가해서 새로운 기능을 업데이트 중입니다.
https://github.com/vercel/next.js/releases

해당 문구를 보면 다음과 같은 경고 문구인데요.
```
next.config.js 파일에서 compiler.styledComponents를 활성화하여 styled-components를 네이티브로 지원하도록 설정할 수 있습니다.
따라서 .babelrc 또는 babel.config.json 파일의 styled-components 관련 설정은 필요하지 않습니다.
```

해당 next.config.js를 보니
```
complier: {
   styledComponents: true
}
```
설정이 이미 되어있는 것으로 확인됩니다.

.babelrc는 지우셔도 무방할 것 같습니다. 해당 파일을 지우고 다시 서버를 내렸다 켰을 때 워닝이 나타나지 않는 것을 확인하실 수 있습니다.

![image](https://github.com/inssagram/FE/assets/24869229/bb551266-3452-42ad-81a3-4c129484313d)

@joshyeom @Daily-manjoo @Februaar
