### ISSUE TITLE
Warn: Image with src has legacy prop "object". Did you forget to run the codemod?

### ISSUE THREAD

**Issue by Daily-manjoo** [inssagram/FE#75]
## Description

https://github.com/inssagram/FE/pull/73

제가 닫은 리퀘스트 요청에 barbel.rc를 지워서 이런 오류들이 갑자기 생겨난 것인지
아직 barbel.rc 삭제 안 하신 다른 분들은 이런 에러가 안뜨는지 여쭙니다.
(작업했어야 하는데 4시간 날림ㅠㅠ)

몇시간 전 기분 좋게 풀리퀘스트 요청을 했으나! 갑자기 터미널에 나타나는 에러 메세지들. 
화면 렌더링엔 문제가 없었으나 리퀘스트 황급히 닫음^^

로컬 진입하자마자 터미널 에러 발생.

Warn: Image with src has legacy prop "objectFit".
Warn: Image with src has legacy prop " layout".

codemod란 패키지를 설치할 수도 있었지만 이 패키지는 npm 버전이라
yarn와 npm을 혼용하면서 쓰면 버전 충돌이 있을 수 있다고 비권장.

## ETC

Warn: Image with src has legacy prop "objectFit"은 해당 스타일을 지우니 해결.

Warn: Image with src has legacy prop " layout". 오류가 뜨는 코드 중에
layout="fill"로 돼있는 것을 fill로 바꾸면 해결. (Next13부터 바뀌었다고 함)

그런데 layout="responsive" width={10} height={10} 이렇게 지정돼있는 것은
fill로 바꾸면 터미널 오류가 사라지긴 하는데 콘솔에 아래와 같은 경고 오류가 생김.

"Image with src 'URL' was detected as the Largest Contentful Paint (LCP)"
= Next.js에서 해당 이미지가 페이지의 가장 큰 콘텐츠로서 페이지 로드 시점에 빠르게 렌더링될 필요가 있으니 이미지 로딩을 우선시 해라
-> priority 속성 추가하니 해당 이미지가 아닌 다른 부분의 사이즈가 커짐ㅠ

- 추가

https://github.com/inssagram/FE/issues/64
이전에 영민님이 터미널 캡쳐를 올려주신것을 보니 제가 직면한 그 경고 문구인데
그냥 무시하고 지나쳐도 됐을 스쳐가는 오류인가 싶습니다.. 허무하고.. 허무하네요...........
업데이트하면서 자연스럽게 뜨는 오류가 맞는건가요 영민님..
그렇다면 긍정적으로 생각하고 자소서에 녹이도록 하겠습니다..

**Comment by joshyeom** [comment]
layout='fill'에서 fill로 바꾸고 objectFit도 지우니 사라졌습니다 개발 당시에는 저렇게 안하면 화면이 엄청 벗어났는데 다시보니 크게 벗어나지 않네요...? 지우고 진행해도 좋을 것 같습니다

4시간이라뇨 ㄷㄷㄷㄷ;;;; 고생하셔뜸;;;;;

**Comment by oinochoe** [comment]
@Daily-manjoo `legacy prop` 경고 문구는 예전 문법 사용한다는 뜻입니다.
https://nextjs.org/docs/pages/api-reference/components/image
여기 공식문서를 보시면 objectFit의 사용방법이 변경되었어요 : ) 
style 속성으로 사용하는 방식으로요..

그리고, fill도 마찬가지로 fill={true}로 변경된 것 보실 수 있지요 : ) 
현재 사용방법이 변경된 방법이 아니라서 그런 듯 합니다.

babel과 무관하게 당연히 뜨는 경고문구이고, 최신 문법을 업데이트하면서 계속해서 변경하는 작업은 현업에서도 패키지 업데이트 때 자주 하는 일이니 참고 해보세요 : )
