### ISSUE TITLE
Feat: Axios Instance

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#79]
## Description
다양하게 Axios를 활용하고 있는가운데 instance로 간단하고 간결하게 요청을 보내보는게 좋을 것 같습니다
아직 서버 연동이 되지 않았기 때문에 header로 token을 받을 경우를 제외하고 body로 get, post, delete, put만 가능하게 만들어 보려고 합니다.

## To-Do
- [x] Axios Instance 구현

**Comment by Februaar** [comment]
api 명세서 나오면 진행하도록 합시다

**Comment by Daily-manjoo** [comment]
지냉시켜
