### ISSUE TITLE
Bug: FOUC 오류 latest by 10/11

### ISSUE THREAD

**Issue by joshyeom** [inssagram/FE#81]
## Description

![](https://shiwoo.dev/_next/image?url=%2Fstatic%2Fimg%2FNext.js%25EC%2597%2590%25EC%2584%259C%2520styled-components%2520%25EC%258A%25A4%25ED%2583%2580%25EC%259D%25BC%25EC%259D%2584%2520%25EB%258A%25A6%25EA%25B2%258C%2520%25EB%25B6%2588%25EB%259F%25AC%25EC%2598%25A4%25EB%258A%2594%2520%25EB%25AC%25B8%25EC%25A0%259C%2520%25ED%2595%25B4%25EA%25B2%25B0%25ED%2595%2598%25EA%25B8%25B0%2Fblink.gif&w=1080&q=100)

위와 같이 우리 페이지도 화면이 css가 늦게 적용되는 현상이 있다.  
## To-Do

- [x] document.js 설정
- [x] getInitaialProps 설정

## ETC

📌 FOUC란?
FOUC(Flash of Unstyled Content)는 브라우저로 웹문서에 접근했을때, 미처 CSS의 스타일이 모두 적용되지 못한 상태에서 화면이 표시되어 발생하는 화면 깜박임, 스타일의 적용 전과 적용 후가 그대로 화면에 노출된 상태로 변경되는 현상등을 일컫는다. 이 현상은 특히 IE(Internet Explorer) 브라우저에서 확인되는데 최신의 IE11에서도 여전히 발생되는 문제이다. 이는 해당 웹문서의 사용자 경험을 떨어뜨리는 요인으로 작용한다.
https://velog.io/@0seo8/ERROR-%ED%8E%98%EC%9D%B4%EC%A7%80%EA%B0%80-%EC%B2%98%EC%9D%8C-%EB%A1%9C%EB%93%9C%EB%90%A0-%EC%8B%9C-%EA%B9%9C%EB%B0%95%EA%B1%B0%EB%A6%AC%EB%8A%94-%EC%9D%B4%EC%8A%88FOUC

10/11
--------------------------------------------------------------------------------------------------------------
- next.config.js
```javascript
const nextConfig = {
  reactStrictMode: true,
  compiler: {
    styledComponents: true,
  },
...
module.exports = nextConfig;
```

- _ document.tsx
```tsx
import Document, { DocumentContext } from 'next/document'
import { ServerStyleSheet } from 'styled-components'

export default class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        })

      const initialProps = await Document.getInitialProps(ctx)
      return {
        ...initialProps,
        styles: [initialProps.styles, sheet.getStyleElement()],
      }
    } finally {
      sheet.seal()
    }
  }
}
```

![image](https://github.com/inssagram/FE/assets/105287510/e1b4e218-d5f0-474e-8eee-a46097e6b9d8)

여러 블로그를 돌아다니고 공식문서에서도 확인하고 해봤는데 안된다... 

10/12
document파일명이 오류가 있었다... 야속하다... 영어단어 공부하러갑니다...

**Comment by Februaar** [comment]
블로그 참고해서 한 번 해볼게여!

**Comment by Februaar** [comment]
영어단어 공부하러 같이 사라집니다...
